// src/app/layout.tsx
import React from 'react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Raph App',
  description: 'Generated by create raph app',
};
import './globals.css'

import TRPCProvider from '@/lib/trpc/Provider';
import AuthProvider from '@/components/AuthProvider';

interface ProvidersProps { children: React.ReactNode }
function Providers({ children }: ProvidersProps) {
  return (
    <AuthProvider>
      <TRPCProvider>
        {children}
      </TRPCProvider>
    </AuthProvider>
  );
}


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
